# Custom Algorithm

## In this tutorial, we provide an example of creaing a new SSL algorithm by resusing the component hook

In [1]:
from semilearn import get_dataset, get_data_loader, get_net_builder, get_algorithm, get_config, Trainer


/media/Zeus/haoc/miniconda/envs/test_semilearn_031/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## Step1: Create and Register Algorithm

We will create a new algorithm based on FixMatch and combine it with entropy loss, using the following steps:

* Inherit FixMatch algorithm
* Rewrite the 'train_step' function by adding entropy loss

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from semilearn.core.utils import ALGORITHMS
from semilearn.algorithms.fixmatch import FixMatch
from inspect import signature



def entropy_loss(ul_y):
    p = F.softmax(ul_y, dim=1)
    return -(p * F.log_softmax(ul_y, dim=1)).sum(dim=1).mean(dim=0)


@ALGORITHMS.register('fixmatch_entropy')
class FixMatchEntropy(FixMatch):
    def train_step(self, idx_lb, x_lb, y_lb, x_ulb_w, x_ulb_s):
        num_lb = y_lb.shape[0]

        # inference and calculate sup/unsup losses
        with self.amp_cm():
            if self.use_cat:
                inputs = torch.cat((x_lb, x_ulb_w, x_ulb_s))
                outputs = self.model(inputs)
                logits_x_lb = outputs['logits'][:num_lb]
                logits_x_ulb_w, logits_x_ulb_s = outputs['logits'][num_lb:].chunk(2)
                feats_x_lb = outputs['feat'][:num_lb]
                feats_x_ulb_w, feats_x_ulb_s = outputs['feat'][num_lb:].chunk(2)
            else:
                outs_x_lb = self.model(x_lb) 
                logits_x_lb = outs_x_lb['logits']
                feats_x_lb = outs_x_lb['feat']
                outs_x_ulb_s = self.model(x_ulb_s)
                logits_x_ulb_s = outs_x_ulb_s['logits']
                feats_x_ulb_s = outs_x_ulb_s['feat']
                with torch.no_grad():
                    outs_x_ulb_w = self.model(x_ulb_w)
                    logits_x_ulb_w = outs_x_ulb_w['logits']
                    feats_x_ulb_w = outs_x_ulb_w['feat']
            feat_dict = {'x_lb':feats_x_lb, 'x_ulb_w':feats_x_ulb_w, 'x_ulb_s':feats_x_ulb_s}

            sup_loss = self.ce_loss(logits_x_lb, y_lb, reduction='mean')
            
            # probs_x_ulb_w = torch.softmax(logits_x_ulb_w, dim=-1)
            probs_x_ulb_w = self.compute_prob(logits_x_ulb_w.detach())
            
            # if distribution alignment hook is registered, call it 
            # this is implemented for imbalanced algorithm - CReST
            if self.registered_hook("DistAlignHook"):
                probs_x_ulb_w = self.call_hook("dist_align", "DistAlignHook", probs_x_ulb=probs_x_ulb_w.detach())

            # compute mask
            mask = self.call_hook("masking", "MaskingHook", logits_x_ulb=probs_x_ulb_w, softmax_x_ulb=False)

            # generate unlabeled targets using pseudo label hook
            pseudo_label = self.call_hook("gen_ulb_targets", "PseudoLabelingHook", 
                                          logits=probs_x_ulb_w,
                                          use_hard_label=self.use_hard_label,
                                          T=self.T,
                                          softmax=False)

            unsup_loss = self.consistency_loss(logits_x_ulb_s,
                                               pseudo_label,
                                               'ce',
                                               mask=mask)
            
            # NOTE: add entropy loss here
            loss_entmin = entropy_loss(logits_x_ulb_w)

            total_loss = sup_loss + self.lambda_u * unsup_loss

        out_dict = self.process_out_dict(loss=total_loss, feat=feat_dict)
        log_dict = self.process_log_dict(sup_loss=sup_loss.item(), 
                                         unsup_loss=unsup_loss.item(), 
                                         total_loss=total_loss.item(), 
                                         util_ratio=mask.float().mean().item())
        return out_dict, log_dict

## Step 2: define configs and create config

In [3]:
config = {
    'algorithm': 'fixmatch_entropy',
    'net': 'vit_tiny_patch2_32',
    'use_pretrain': True, 
    'pretrain_path': 'https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/vit_tiny_patch2_32_mlp_im_1k_32.pth',

    # optimization configs
    'epoch': 1,  # set to 100
    'num_train_iter': 5000,  # set to 102400
    'num_eval_iter': 500,   # set to 1024
    'num_log_iter': 50,    # set to 256
    'optim': 'AdamW',
    'lr': 5e-4,
    'layer_decay': 0.5,
    'batch_size': 16,
    'eval_batch_size': 16,


    # dataset configs
    'dataset': 'cifar10',
    'num_labels': 40,
    'num_classes': 10,
    'img_size': 32,
    'crop_ratio': 0.875,
    'data_dir': './data',
    'ulb_samples_per_class': None,

    # algorithm specific configs
    'hard_label': True,
    'uratio': 2,
    'ulb_loss_ratio': 1.0,

    # device configs
    'gpu': 0,
    'world_size': 1,
    'distributed': False,
    "num_workers": 2,
}
config = get_config(config)

/bin/sh: 1: netstat: not found


## Step 3: create algorithm and dataset

In [4]:
algorithm = get_algorithm(config,  get_net_builder(config.net, from_name=False), tb_log=None, logger=None)

Files already downloaded and verified
lb count: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
ulb count: [5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000]
Files already downloaded and verified
unlabeled data number: 50000, labeled data number 40
Create train and test data loaders
[!] data loader keys: dict_keys(['train_lb', 'train_ulb', 'eval'])
_IncompatibleKeys(missing_keys=['head.weight', 'head.bias'], unexpected_keys=[])
Create optimizer and scheduler


In [5]:
dataset_dict = get_dataset(config, config.algorithm, config.dataset, config.num_labels, config.num_classes, data_dir=config.data_dir, include_lb_to_ulb=config.include_lb_to_ulb)
train_lb_loader = get_data_loader(config, dataset_dict['train_lb'], config.batch_size)
train_ulb_loader = get_data_loader(config, dataset_dict['train_ulb'], int(config.batch_size * config.uratio))
eval_loader = get_data_loader(config, dataset_dict['eval'], config.eval_batch_size)

Files already downloaded and verified
lb count: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
ulb count: [5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000]
Files already downloaded and verified


## Step 4: train and evaluate

In [6]:
# training and evaluation
trainer = Trainer(config, algorithm)
trainer.fit(train_lb_loader, train_ulb_loader, eval_loader)
trainer.evaluate(eval_loader)

Epoch: 0
50 iteration USE_EMA: True, train/sup_loss: 3.5051, train/unsup_loss: 0.0000, train/total_loss: 3.5051, train/util_ratio: 0.0000, train/run_time: 0.1370, lr: 0.0005, train/prefecth_time: 0.0036 
100 iteration USE_EMA: True, train/sup_loss: 1.0864, train/unsup_loss: 0.0000, train/total_loss: 1.0864, train/util_ratio: 0.0000, train/run_time: 0.1388, lr: 0.0005, train/prefecth_time: 0.0031 
150 iteration USE_EMA: True, train/sup_loss: 0.5159, train/unsup_loss: 0.0000, train/total_loss: 0.5159, train/util_ratio: 0.0000, train/run_time: 0.1384, lr: 0.0005, train/prefecth_time: 0.0035 
200 iteration USE_EMA: True, train/sup_loss: 0.5048, train/unsup_loss: 0.0000, train/total_loss: 0.5048, train/util_ratio: 0.0000, train/run_time: 0.1384, lr: 0.0005, train/prefecth_time: 0.0037 
250 iteration USE_EMA: True, train/sup_loss: 0.5692, train/unsup_loss: 0.1162, train/total_loss: 0.6854, train/util_ratio: 0.1562, train/run_time: 0.1395, lr: 0.0005, train/prefecth_time: 0.0037 
300 iteratio

/media/Zeus/haoc/miniconda/envs/test_semilearn_031/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


confusion matrix:
[[0.    0.    0.    0.    0.    0.    0.    1.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    1.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    1.    0.    0.   ]
 [0.    0.    0.    0.004 0.    0.001 0.    0.995 0.    0.   ]
 [0.    0.    0.    0.002 0.    0.    0.    0.998 0.    0.   ]
 [0.    0.    0.    0.001 0.    0.014 0.    0.985 0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    1.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    1.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    1.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    1.    0.    0.   ]]
model saved: ./saved_models/fixmatch/latest_model.pth
model saved: ./saved_models/fixmatch/model_best.pth
500 iteration, USE_EMA: True, train/sup_loss: 0.0129, train/unsup_loss: 0.0249, train/total_loss: 0.0378, train/util_ratio: 0.1250, train/run_time: 0.1401, eval/loss: 5.5155, eval/top-1-acc: 0.1018, eval/balanced_acc: 0.1018, eval/precision: 0.1

/media/Zeus/haoc/miniconda/envs/test_semilearn_031/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


confusion matrix:
[[0.303 0.    0.006 0.004 0.    0.003 0.    0.645 0.    0.039]
 [0.    0.001 0.    0.    0.    0.001 0.    0.292 0.    0.706]
 [0.    0.    0.506 0.018 0.    0.11  0.    0.361 0.    0.005]
 [0.    0.    0.001 0.495 0.    0.263 0.    0.239 0.    0.002]
 [0.001 0.    0.005 0.061 0.    0.123 0.    0.809 0.    0.001]
 [0.    0.    0.    0.031 0.    0.78  0.    0.189 0.    0.   ]
 [0.001 0.    0.028 0.064 0.    0.231 0.002 0.67  0.    0.004]
 [0.    0.    0.    0.004 0.    0.127 0.    0.868 0.    0.001]
 [0.036 0.    0.004 0.004 0.    0.031 0.    0.677 0.    0.248]
 [0.    0.    0.    0.002 0.    0.001 0.    0.121 0.    0.876]]
model saved: ./saved_models/fixmatch/latest_model.pth
model saved: ./saved_models/fixmatch/model_best.pth
1000 iteration, USE_EMA: True, train/sup_loss: 0.0189, train/unsup_loss: 0.2167, train/total_loss: 0.2356, train/util_ratio: 0.5000, train/run_time: 0.1406, eval/loss: 2.4450, eval/top-1-acc: 0.3831, eval/balanced_acc: 0.3831, eval/precision: 0.

[2023-07-19 23:45:48,260 INFO] confusion matrix
[2023-07-19 23:45:48,261 INFO] [[0.969 0.001 0.    0.001 0.    0.    0.001 0.001 0.018 0.009]
 [0.    0.987 0.    0.    0.    0.    0.    0.    0.    0.013]
 [0.049 0.    0.776 0.007 0.127 0.017 0.016 0.007 0.    0.001]
 [0.003 0.001 0.006 0.869 0.013 0.072 0.027 0.006 0.002 0.001]
 [0.    0.    0.    0.002 0.974 0.001 0.004 0.018 0.001 0.   ]
 [0.    0.    0.001 0.045 0.011 0.916 0.003 0.024 0.    0.   ]
 [0.004 0.    0.001 0.001 0.001 0.001 0.991 0.    0.001 0.   ]
 [0.006 0.    0.002 0.006 0.127 0.059 0.    0.798 0.    0.002]
 [0.014 0.007 0.    0.    0.    0.    0.    0.    0.973 0.006]
 [0.005 0.018 0.    0.    0.    0.    0.    0.    0.002 0.975]]
[2023-07-19 23:45:48,264 INFO] evaluation metric
[2023-07-19 23:45:48,264 INFO] acc: 0.9228
[2023-07-19 23:45:48,265 INFO] precision: 0.9283
[2023-07-19 23:45:48,266 INFO] recall: 0.9228
[2023-07-19 23:45:48,266 INFO] f1: 0.9223


model saved: ./saved_models/fixmatch/latest_model.pth


[2023-07-19 23:45:50,377 INFO] Best acc 0.9228 at epoch 0
[2023-07-19 23:45:50,378 INFO] Training finished.


model saved: ./saved_models/fixmatch/model_best.pth


[2023-07-19 23:46:52,956 INFO] confusion matrix
[2023-07-19 23:46:52,958 INFO] [[0.969 0.001 0.    0.001 0.    0.    0.001 0.001 0.018 0.009]
 [0.    0.987 0.    0.    0.    0.    0.    0.    0.    0.013]
 [0.049 0.    0.776 0.007 0.127 0.017 0.016 0.007 0.    0.001]
 [0.003 0.001 0.006 0.869 0.013 0.072 0.027 0.006 0.002 0.001]
 [0.    0.    0.    0.002 0.974 0.001 0.004 0.018 0.001 0.   ]
 [0.    0.    0.001 0.045 0.011 0.916 0.003 0.024 0.    0.   ]
 [0.004 0.    0.001 0.001 0.001 0.001 0.991 0.    0.001 0.   ]
 [0.006 0.    0.002 0.006 0.127 0.059 0.    0.798 0.    0.002]
 [0.014 0.007 0.    0.    0.    0.    0.    0.    0.973 0.006]
 [0.005 0.018 0.    0.    0.    0.    0.    0.    0.002 0.975]]
[2023-07-19 23:46:52,961 INFO] evaluation metric
[2023-07-19 23:46:52,961 INFO] acc: 0.9228
[2023-07-19 23:46:52,962 INFO] precision: 0.9283
[2023-07-19 23:46:52,963 INFO] recall: 0.9228
[2023-07-19 23:46:52,963 INFO] f1: 0.9223


{'acc': 0.9228,
 'precision': 0.928316578833672,
 'recall': 0.9228,
 'f1': 0.9223419792678316}